services:
  - type: web
    name: language-translator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        fromGroup: gemini-credentials
      - key: PYTHON_VERSION
        value: 3.9.7
